Standard Green:
	TEXT_COLOR: FG_GREEN
	NUM_COLOR = FG_BRIGHT_WHITE;
	BG_COLOR = TRANSPARENT
	SYMBOLS = FG_BRIGHT_BLUE
	CAPITALISE = 0
	BLOCK_LETT = 0;

Bright Green:
	TEXT_COLOR = FG_BRIGHT_GREEN
	NUM_COLOR = FG_BRIGHT_BLUE
	BG_COLOR = TRANSPARENT
	SYMBOLS = FG_BRIGHT_BLUE
	CAPITALISE = 0;
	BLOCK_LETT = 0

Normal:
	TEXT_COLOR = NORMAL;
	NUM_COLOR = NORMAL;
	BG_COLOR = NORMAL;
	SYMBOLS = NORMAL;
	CAPITALISE = 0;
	BLOCK_LETT = 0

Red Dead:
	TEXT_COLOR = FG_BRIGHT_RED;
	NUM_COLOR = FG_BRIGHT_GREEN;
	BG_COLOR = TRANSPARENT;
	SYMBOLS = NORMAL;
	CAPITALISE = 0;
	BLOCK_LETT = 1
